/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientJFrame.java
 *
 * Created on 2012-11-19, 14:13:27
 */
package ui;

import communication.Communication;
import java.awt.Color;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import utils.Business;
import utils.BusinessStatusTableModel;
import utils.Configuarator;
import utils.Constants;

/**
 *
 * @author martin
 */
public class ClientJFrame extends javax.swing.JFrame {

    Configuarator conf;
    Constants constant;
    private BusinessStatusTableModel bstm;
    private Communication comm;

    /**
     * Creates new form ClientJFrame
     */
    public ClientJFrame() {
        initComponents();
        loadConf();

        bstm = new BusinessStatusTableModel();
        busiTable.setModel(bstm);
        setRemoteStationID();
        setMODEMnumber();
        setVideo();
        comm = new Communication(this);

        this.setSize(1280, 800);
        int w = (Toolkit.getDefaultToolkit().getScreenSize().width - 1280) / 2;
        int h = (Toolkit.getDefaultToolkit().getScreenSize().height - 800) / 2;
        this.setLocation(w, h);
        this.setTitle("[站点" + constant.getId() + "]");
    }

    private void loadConf() {
        conf = new Configuarator();
        constant = new Constants();
        constant.setId(conf.getId());
        constant.setRemoteIP(conf.getRemoteIP());
        constant.setRemotePort(Integer.parseInt(conf.getRemotePort()));
//        constant.setRemoteLoginPort(Integer.parseInt(conf.getRemoteLoginPort()));
//        constant.setRemoteMessagePort(Integer.parseInt(conf.getRemoteMessagePort()));
        constant.setBizBoardPort(Integer.parseInt(conf.getBusinessBoardPort()));
        constant.setBizBoardIP(conf.getBusinessBoardIP());
        constant.setBdFax(Integer.parseInt(conf.getBdFax()));
        constant.setBdVideoHD(Integer.parseInt(conf.getBdVideoHD()));
        constant.setBdVideoNormal(Integer.parseInt(conf.getBdVideoNormal()));
        constant.setBdVoIP(Integer.parseInt(conf.getBdVoIP()));
        constant.setSiteNum(Integer.parseInt(conf.getSiteNum()));
//        System.out.println(constant.getRemoteIP());
//        System.out.println(constant.getRemoteLoginPort());
//        System.out.println(constant.getRemoteMessagePort());
//        System.out.println(constant.getBizBoardIP());
//        System.out.println(constant.getBizBoardPort());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        msg_send = new javax.swing.JButton();
        msg_clear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        msg_record = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        msg_input = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        busi_application = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tfBandWidth = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfFaxNum = new javax.swing.JTextField();
        cbRemoteId = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbModemType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbVideo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        tfVoipNum = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfAntennaCaliber = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfAmplifier = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        busi_submit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        busi_status = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        busiTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        link_log = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lbConnectStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 662));
        jPanel2.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 30, 0));
        jPanel3.add(jLabel3);

        msg_send.setText("发送");
        msg_send.setEnabled(false);
        msg_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_sendActionPerformed(evt);
            }
        });
        jPanel3.add(msg_send);

        msg_clear.setText("清空");
        msg_clear.setEnabled(false);
        msg_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_clearActionPerformed(evt);
            }
        });
        jPanel3.add(msg_clear);
        jPanel3.add(jLabel4);

        jPanel2.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "消息记录", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(146, 300));

        msg_record.setEditable(false);
        msg_record.setColumns(20);
        msg_record.setLineWrap(true);
        msg_record.setRows(5);
        jScrollPane3.setViewportView(msg_record);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.NORTH);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "消息输入框", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(146, 200));

        msg_input.setColumns(20);
        msg_input.setLineWrap(true);
        msg_input.setRows(5);
        jScrollPane4.setViewportView(msg_input);

        jPanel2.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        busi_application.setPreferredSize(new java.awt.Dimension(300, 382));
        busi_application.setLayout(new java.awt.BorderLayout(0, 10));

        tfBandWidth.setText("512");

        jLabel5.setText("VoIP电话路数：");

        jLabel6.setText("视频服务质量：");

        tfFaxNum.setText("2");

        cbRemoteId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("互联网带宽：");

        jLabel8.setText("传真路数：");

        cbModemType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("调制解调器：");

        jLabel10.setText("kbps");

        cbVideo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("远端站号：");

        tfVoipNum.setText("2");

        jLabel15.setText("天线口径：");

        tfAntennaCaliber.setText("2");

        jLabel16.setText("功放大小：");

        tfAmplifier.setText("2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(42, 42, 42)
                            .addComponent(cbRemoteId, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(cbModemType, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(42, 42, 42)
                                    .addComponent(tfAntennaCaliber, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(42, 42, 42)
                                        .addComponent(tfAmplifier, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfVoipNum, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(tfBandWidth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addComponent(tfFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cbVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(476, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbRemoteId))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbModemType))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfAntennaCaliber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfAmplifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfVoipNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfBandWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbVideo))
                .addGap(99, 99, 99))
        );

        busi_application.add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));
        jPanel5.add(jLabel7);
        jPanel5.add(jLabel11);

        busi_submit.setText("提交");
        busi_submit.setEnabled(false);
        busi_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busi_submitActionPerformed(evt);
            }
        });
        jPanel5.add(busi_submit);
        jPanel5.add(jLabel12);
        jPanel5.add(jLabel13);
        jPanel5.add(jLabel14);

        busi_application.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("业务申请", busi_application);

        busi_status.setLayout(new java.awt.BorderLayout(0, 10));

        busiTable.setAutoCreateRowSorter(true);
        busiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "512kbpbs", "xxdb", "xxdb ", "入网", "2", "0、高清", "1", "2MB/s", "17:50:22", null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "远端站点", "带宽", "信道1信噪比", "信道2信噪比", "入网状况", "VoIP路数", "视频业务", "传真路数", "互联网带宽", "状态更新时间", "业务申请状况"
            }
        ));
        busiTable.setColumnSelectionAllowed(true);
        busiTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane5.setViewportView(busiTable);
        busiTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        busi_status.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "连接记录", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(146, 150));

        link_log.setColumns(20);
        link_log.setRows(5);
        jScrollPane1.setViewportView(link_log);

        busi_status.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("运行状况", busi_status);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lbConnectStatus.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        lbConnectStatus.setForeground(java.awt.Color.red);
        lbConnectStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbConnectStatus.setText("连接状态：未连接");
        jPanel1.add(lbConnectStatus, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busi_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busi_submitActionPerformed
        // TODO add your handling code here:
//        Random rdm = new Random();
        Business bz = new Business();
        bz.setStationID(this.cbRemoteId.getSelectedItem().toString());
        bz.setSigNoiseRatio1("" + constant.getSigNoiseLocal());
        bz.setSignoiseRatio2("" + constant.getSigNoiseRemote());
        bz.setRuningStatus("入网");

        int voipNum = Integer.parseInt(tfVoipNum.getText());
        bz.setVoIPNum("" + voipNum);
        int voipBd = voipNum * constant.getBdVoIP();

        String videoSelected = cbVideo.getSelectedItem().toString();
        bz.setVideoBusi(videoSelected);
        int videoBd = 0;
        if (videoSelected.equals("0")) {
            videoBd = 0;
        } else if (videoSelected.equals("标清")) {
            videoBd = constant.getBdVideoNormal();
        } else if (videoSelected.equals("高清")) {
            videoBd = constant.getBdVideoHD();
        }

        int faxNum = Integer.parseInt(tfFaxNum.getText());
        bz.setFaxNum("" + faxNum);
        int faxBd = faxNum * constant.getBdFax();

        int internetBd = Integer.parseInt(tfBandWidth.getText());
        bz.setInterBandwidth(internetBd + "kbps");

        int bandWidth = voipBd + videoBd + faxBd + internetBd;
        bz.setBandwidth(bandWidth + "kbps");

        bz.setAntennaCaliber(tfAntennaCaliber.getText());
        bz.setAmplifier(tfAmplifier.getText());
        bz.setFreshTime((new SimpleDateFormat("yyyy-MM-dd HH:mm:ss")).format(new Date()));
        bz.setAppStatus("正在申请");
        bstm.addRecord(bz);

        String request = "request:";
        String idCalled = cbRemoteId.getSelectedItem().toString();
        String biz = "话音" + tfVoipNum.getText() + "路&视频" + cbVideo.getSelectedItem().toString();
//        String bd = tfBandWidth.getText();
        request += constant.getId() + ":" + idCalled + ":" + biz + ":" + bandWidth + ":" + bz.getSerial();
//        System.out.println("query: " + request);
//        System.out.println(cbVideo.getSelectedItem().toString());
        comm.sendRequest(request);

    }//GEN-LAST:event_busi_submitActionPerformed

    private void msg_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_sendActionPerformed
        // TODO add your handling code here:
        String str = this.msg_input.getText();
        if (!str.equals("")) {
            String message = "message:";
            msg_record.append("[本机]:" + str + "\n");
            message += constant.getId() + ":" + str;
            comm.sendMessage(message);
            this.msg_input.setText("");
        }


    }//GEN-LAST:event_msg_sendActionPerformed

    private void msg_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_clearActionPerformed
        // TODO add your handling code here:
        this.msg_input.setText("");
    }//GEN-LAST:event_msg_clearActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientJFrame().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable busiTable;
    private javax.swing.JPanel busi_application;
    private javax.swing.JPanel busi_status;
    public javax.swing.JButton busi_submit;
    private javax.swing.JComboBox cbModemType;
    private javax.swing.JComboBox cbRemoteId;
    private javax.swing.JComboBox cbVideo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbConnectStatus;
    private javax.swing.JTextArea link_log;
    private javax.swing.JButton msg_clear;
    private javax.swing.JTextArea msg_input;
    private javax.swing.JTextArea msg_record;
    private javax.swing.JButton msg_send;
    private javax.swing.JTextField tfAmplifier;
    private javax.swing.JTextField tfAntennaCaliber;
    private javax.swing.JTextField tfBandWidth;
    private javax.swing.JTextField tfFaxNum;
    private javax.swing.JTextField tfVoipNum;
    // End of variables declaration//GEN-END:variables

    private void setRemoteStationID() {
//        String item[] = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"};
        int siteNum = constant.getSiteNum();
        String item[] = new String[siteNum];
        for (int i = 0; i < siteNum; i++) {
            item[i] = "" + (i + 1);
        }
        this.cbRemoteId.setMaximumRowCount(6);
        this.cbRemoteId.setModel(new javax.swing.DefaultComboBoxModel(item));
    }

    private void setMODEMnumber() {
        String item[] = {"1", "2", "3", "4"};
        this.cbModemType.setMaximumRowCount(4);
        this.cbModemType.setModel(new javax.swing.DefaultComboBoxModel(item));
    }

    private void setVideo() {
        String item[] = {"0", "标清", "高清"};
        this.cbVideo.setModel(new DefaultComboBoxModel(item));
    }

    public Constants getConstants() {
        return constant;
    }
//    public int getPrivilege() {
//        return privilege;
//    }

    public void connected() {
        msg_send.setEnabled(true);
        msg_input.setEditable(true);
        msg_clear.setEnabled(true);
        busi_submit.setEnabled(true);
        link_log.append((new SimpleDateFormat("yyyy-MM-dd HH:mm:ss")).format(new Date()) + "与服务器连接成功" + "\n");
        lbConnectStatus.setText("连接状态：已连接");
        lbConnectStatus.setForeground(Color.green);
    }

    public void unconnected() {
        msg_send.setEnabled(false);
        msg_input.setEditable(false);
        msg_clear.setEnabled(false);
        busi_submit.setEnabled(false);
        link_log.append((new SimpleDateFormat("yyyy-MM-dd HH:mm:ss")).format(new Date()) + "与服务器断开连接" + "\n");
        lbConnectStatus.setText("连接状态：未连接");
        lbConnectStatus.setForeground(Color.red);
    }

    public void appendMessage(String str) {
        msg_record.append("[服务器]: " + str + "\n");
    }

//    public void processBizEcho(String type, String serial) {
//        int t = Integer.parseInt(type);
//        int s = Integer.parseInt(serial);
//        String status = null;
//        switch (t) {
//            case 0:
//                status = "已批准";
//                break;
//            case 1:
//                status = "已驳回";
//                break;
//            case 2:
//                status = "已警告";
//                break;
//            case 3:
//                status = "已拆除";
//                break;
//        }
//        bstm.setRunningStatus(s, status);
//    }
     public void processBizEcho(String s) {
         String[] strs = s.split(":");
        int type = Integer.parseInt(strs[0]);
        int serial = Integer.parseInt(strs[1]);
        String status = null;
        switch (type) {
            case 0:
                status = "已批准";
                String fp = strs[2];
                String cf = "F7:03:"+fp+":"+bstm.getBandwidth(serial)+":"+"35"+":"+"00";
                System.out.println(cf);
                comm.sendBizBoardQuery(cf);
                break;
            case 1:
                status = "已驳回";
                break;
            case 2:
                status = "已警告";
                break;
            case 3:
                status = "已拆除";
                break;
        }
        bstm.setRunningStatus(serial, status);
    }
     
     public void updateSNR(int snr){
         bstm.updateSNR(snr);
     }
}
